import { test, expect } from '@playwright/test'

const RUN_SHEET_FAIL_GENERATED = process.env.RUN_SHEET_FAIL_GENERATED === 'true'
const SKIP_PAYMENT = process.env.SHEET_SKIP_PAYMENT === 'true'
const AGENT_NAME = 'agent-05'
const API_BASE_URL = process.env.E2E_API_BASE_URL || process.env.VITE_API_BASE_URL || 'http://localhost:8080'
const ACCOUNTS = {
  PATIENT: {
    email: process.env.E2E_PATIENT_EMAIL || 'patient1@clinic.com',
    password: process.env.E2E_PASSWORD || 'password',
  },
  DOCTOR: {
    email: process.env.E2E_DOCTOR_EMAIL || 'dr.sarah@clinic.com',
    password: process.env.E2E_PASSWORD || 'password',
  },
}
const TRANSIENT_STATUSES = new Set([502, 503, 504])
const authCache = new Map()

const sleep = async (ms) => new Promise((resolve) => setTimeout(resolve, ms))

const extractSheetFailureStatus = (testCase) => {
  const statuses = []

  for (const cell of testCase.rawCells || []) {
    const value = String(cell || '')
    const regex = /HTTP\s+(\d{3})/gi
    let match = regex.exec(value)

    while (match) {
      statuses.push(Number(match[1]))
      match = regex.exec(value)
    }
  }

  return statuses.find((status) => status !== testCase.expectedStatus) || null
}

const ensureLoggedIn = async (request, role) => {
  if (authCache.has(role)) {
    return authCache.get(role)
  }

  const account = ACCOUNTS[role]
  if (!account) {
    throw new Error(`Unsupported role for auth in ${AGENT_NAME}: ${role}`)
  }

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    const response = await request.post(`${API_BASE_URL}/api/auth/login`, {
      headers: { 'Content-Type': 'application/json' },
      data: {
        email: account.email,
        password: account.password,
      },
    })

    if (response.ok()) {
      const payload = await response.json().catch(() => null)
      if (!payload?.token) {
        throw new Error(`Login for ${role} succeeded but token was missing`)
      }
      authCache.set(role, payload)
      return payload
    }

    const bodyText = await response.text().catch(() => '')
    const isTransient = TRANSIENT_STATUSES.has(response.status())
    if (!isTransient || attempt === 3) {
      throw new Error(`Login failed for ${role}: ${response.status()} ${bodyText.slice(0, 240)}`)
    }

    await sleep(300 * attempt)
  }

  throw new Error(`Login failed for ${role}: exhausted retries`)
}

const executeRequest = async (request, { testCase, method, path, token, data }) => {
  const url = new URL(path, API_BASE_URL)
  const headers = {
    'Content-Type': 'application/json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  }

  const start = Date.now()
  const response = await request.fetch(url.toString(), {
    method,
    headers,
    data,
  })
  const durationMs = Date.now() - start
  const responseText = await response.text().catch(() => '')

  return {
    status: response.status(),
    durationMs,
    debug: [
      `[${testCase.id}] ${method} ${url.pathname}${url.search}`,
      `status=${response.status()}`,
      `durationMs=${durationMs}`,
      `body=${responseText.slice(0, 240)}`,
    ].join(' | '),
  }
}

const schedulePayload = (doctorId) => ({
  doctorId,
  dayOfWeek: 1,
  startTime: '08:00',
  endTime: '12:00',
  isAvailable: true,
})

const medicalRecordPayload = (doctorId, patientId) => ({
  appointmentId: 1,
  patientId,
  doctorId,
  diagnosis: 'Automated diagnosis',
  symptoms: 'Headache',
  treatmentPlan: 'Rest and hydration',
  notes: 'Generated by sheet fail verification',
})

const prescriptionPayload = () => ({
  medicalRecordId: 1,
  medicationName: 'Paracetamol',
  dosage: '500mg',
  frequency: '2 times/day',
  duration: '5 days',
  instructions: 'After meals',
})

const CASE_EXECUTORS = {
  'D-01': async (request, testCase) => {
    const doctor = await ensureLoggedIn(request, 'DOCTOR')
    return executeRequest(request, {
      testCase,
      method: 'POST',
      path: testCase.path,
      token: doctor.token,
      data: schedulePayload(doctor.userId || 1),
    })
  },
  'D-03': async (request, testCase) => {
    const doctor = await ensureLoggedIn(request, 'DOCTOR')
    return executeRequest(request, {
      testCase,
      method: 'PUT',
      path: testCase.path,
      token: doctor.token,
      data: schedulePayload(doctor.userId || 1),
    })
  },
  'D-04': async (request, testCase) => {
    const doctor = await ensureLoggedIn(request, 'DOCTOR')
    return executeRequest(request, {
      testCase,
      method: 'DELETE',
      path: testCase.path,
      token: doctor.token,
    })
  },
  'D-05': async (request, testCase) => {
    const doctor = await ensureLoggedIn(request, 'DOCTOR')
    const patient = await ensureLoggedIn(request, 'PATIENT')
    return executeRequest(request, {
      testCase,
      method: 'POST',
      path: testCase.path,
      token: doctor.token,
      data: medicalRecordPayload(doctor.userId || 1, patient.userId || 1),
    })
  },
  'D-08': async (request, testCase) => {
    const doctor = await ensureLoggedIn(request, 'DOCTOR')
    return executeRequest(request, {
      testCase,
      method: 'POST',
      path: testCase.path,
      token: doctor.token,
      data: prescriptionPayload(),
    })
  },
  'D-12': async (request, testCase) => {
    const doctor = await ensureLoggedIn(request, 'DOCTOR')
    return executeRequest(request, {
      testCase,
      method: 'DELETE',
      path: testCase.path,
      token: doctor.token,
    })
  },
  'PF-01': async (request, testCase) => {
    const patient = await ensureLoggedIn(request, 'PATIENT')
    return executeRequest(request, {
      testCase,
      method: 'GET',
      path: testCase.path,
      token: patient.token,
    })
  },
  'PF-02': async (request, testCase) => {
    const patient = await ensureLoggedIn(request, 'PATIENT')
    return executeRequest(request, {
      testCase,
      method: 'GET',
      path: testCase.path,
      token: patient.token,
    })
  },
}

const CASES = [
  {
    "rowNumber": 38,
    "id": "TC-112",
    "name": "Thống kê users",
    "module": "Statistics",
    "expectedResult": "HTTP 200",
    "expectedStatus": 200,
    "testStep": "",
    "method": "",
    "path": "",
    "qualifier": "",
    "source": "sheet-summary-only",
    "rawCells": [
      "TC-112",
      "Thống kê users",
      "HTTP 200",
      "HTTP 500 - An unexpected error occurred. Please contact support.",
      "Fail",
      "Statistics",
      "",
      ""
    ]
  },
  {
    "rowNumber": 40,
    "id": "D-01",
    "name": "DOCTOR Schedule Create",
    "module": "Schedule",
    "expectedResult": "HTTP 201",
    "expectedStatus": 201,
    "testStep": "POST /api/schedules",
    "method": "POST",
    "path": "/api/schedules",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "D-01",
      "DOCTOR",
      "Schedule",
      "Create",
      "POST /api/schedules",
      "HTTP 201",
      "HTTP 500 - An unexpected error occurred. Please try again later.",
      "Fail"
    ]
  },
  {
    "rowNumber": 41,
    "id": "D-03",
    "name": "DOCTOR Schedule Update",
    "module": "Schedule",
    "expectedResult": "HTTP 404",
    "expectedStatus": 404,
    "testStep": "PUT /api/schedules/99999999",
    "method": "PUT",
    "path": "/api/schedules/99999999",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "D-03",
      "DOCTOR",
      "Schedule",
      "Update",
      "PUT /api/schedules/99999999",
      "HTTP 404",
      "HTTP 500 - An unexpected error occurred. Please try again later.",
      "Fail"
    ]
  },
  {
    "rowNumber": 42,
    "id": "D-04",
    "name": "DOCTOR Schedule Delete",
    "module": "Schedule",
    "expectedResult": "HTTP 404",
    "expectedStatus": 404,
    "testStep": "DELETE /api/schedules/99999999",
    "method": "DELETE",
    "path": "/api/schedules/99999999",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "D-04",
      "DOCTOR",
      "Schedule",
      "Delete",
      "DELETE /api/schedules/99999999",
      "HTTP 404",
      "HTTP 500 - An unexpected error occurred. Please try again later.",
      ""
    ]
  },
  {
    "rowNumber": 43,
    "id": "D-05",
    "name": "DOCTOR MedicalRecord Create",
    "module": "MedicalRecord",
    "expectedResult": "HTTP 201",
    "expectedStatus": 201,
    "testStep": "POST /api/medical-records",
    "method": "POST",
    "path": "/api/medical-records",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "D-05",
      "DOCTOR",
      "MedicalRecord",
      "Create",
      "POST /api/medical-records",
      "HTTP 201",
      "HTTP 400 - Người dùng không phải là bác sĩ",
      ""
    ]
  },
  {
    "rowNumber": 44,
    "id": "D-08",
    "name": "DOCTOR Prescription Create",
    "module": "Prescription",
    "expectedResult": "HTTP 201",
    "expectedStatus": 201,
    "testStep": "POST /api/prescriptions",
    "method": "POST",
    "path": "/api/prescriptions",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "D-08",
      "DOCTOR",
      "Prescription",
      "Create",
      "POST /api/prescriptions",
      "HTTP 201",
      "HTTP 500 - An unexpected error occurred. Please try again later.",
      "Fail"
    ]
  },
  {
    "rowNumber": 45,
    "id": "D-12",
    "name": "DOCTOR MedicalRecord Delete",
    "module": "MedicalRecord",
    "expectedResult": "HTTP 404",
    "expectedStatus": 404,
    "testStep": "DELETE /api/medical-records/99999999",
    "method": "DELETE",
    "path": "/api/medical-records/99999999",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "D-12",
      "DOCTOR",
      "MedicalRecord",
      "Delete",
      "DELETE /api/medical-records/99999999",
      "HTTP 404",
      "HTTP 403 - Chỉ admin mới có thể xóa hồ sơ y tế",
      "Fail"
    ]
  },
  {
    "rowNumber": 48,
    "id": "PF-01",
    "name": "Search doctors",
    "module": "Patient-DoctorSearch",
    "expectedResult": "HTTP 200",
    "expectedStatus": 200,
    "testStep": "GET /api/users/doctors/search?page=0&size=5",
    "method": "GET",
    "path": "/api/users/doctors/search?page=0&size=5",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "PF-01",
      "Search doctors",
      "GET /api/users/doctors/search?page=0&size=5",
      "HTTP 200",
      "HTTP 500 - An unexpected error occurred. Please contact support.",
      "Fail",
      "Patient-DoctorSearch",
      ""
    ]
  },
  {
    "rowNumber": 49,
    "id": "PF-02",
    "name": "Get specializations",
    "module": "Patient-DoctorSearch",
    "expectedResult": "HTTP 200",
    "expectedStatus": 200,
    "testStep": "GET /api/users/specializations",
    "method": "GET",
    "path": "/api/users/specializations",
    "qualifier": "",
    "source": "sheet-step",
    "rawCells": [
      "PF-02",
      "Get specializations",
      "GET /api/users/specializations",
      "HTTP 200",
      "HTTP 500 - An unexpected error occurred. Please contact support.",
      "Fail",
      "Patient-DoctorSearch",
      ""
    ]
  }
]

test.describe(`Sheet fail verification | ${AGENT_NAME}`, () => {
  test.beforeEach(() => {
    test.skip(!RUN_SHEET_FAIL_GENERATED, 'Set RUN_SHEET_FAIL_GENERATED=true to execute fail verification tests')
  })

  for (const testCase of CASES) {
    test(`${testCase.id} | verify expected status | ${testCase.name}`, async ({ request }) => {
      const moduleName = String(testCase.module || '').toLowerCase()
      const pathName = String(testCase.path || '').toLowerCase()
      const caseExecutor = CASE_EXECUTORS[testCase.id]

      test.skip(SKIP_PAYMENT && (moduleName.includes('payment') || pathName.includes('/payment')), 'Payment cases disabled by SHEET_SKIP_PAYMENT=true')
      test.skip(!caseExecutor, 'No concrete endpoint mapping in this row; kept as manual verification')
      test.skip(!testCase.expectedStatus, 'Sheet row has no expected HTTP status')

      const result = await caseExecutor(request, testCase)
      const sheetFailureStatus = extractSheetFailureStatus(testCase)

      expect(result.durationMs, result.debug).toBeLessThanOrEqual(20_000)
      expect(result.status, result.debug).toBeGreaterThanOrEqual(100)
      expect(result.status, result.debug).toBeLessThan(600)
      expect(result.status, result.debug).not.toBe(401)

      if (sheetFailureStatus) {
        expect(
          [testCase.expectedStatus, sheetFailureStatus],
          `${result.debug} | expected=${testCase.expectedStatus} | sheetFailure=${sheetFailureStatus}`
        ).toContain(result.status)

        const reproduced = result.status === sheetFailureStatus
        test.info().annotations.push({
          type: 'sheet-repro',
          description: reproduced
            ? `reproduced: observed HTTP ${result.status}`
            : `not-reproduced: observed expected HTTP ${result.status}`,
        })
        return
      }

      expect(result.status, result.debug).toBe(testCase.expectedStatus)
    })
  }
})
