import { test, expect } from '@playwright/test'
import { executeSheetCase } from '../../helpers/sheet-generated-api.js'

const RUN_SHEET_GENERATED = process.env.RUN_SHEET_GENERATED === 'true'
const AGENT_NAME = 'agent-09'
const API_BASE_URL = process.env.E2E_API_BASE_URL || process.env.VITE_API_BASE_URL || 'http://localhost:8080'
const PATIENT_EMAIL = process.env.E2E_PATIENT_EMAIL || 'patient1@clinic.com'
const E2E_PASSWORD = process.env.E2E_PASSWORD || 'password'
const DEFAULT_IDS = {
  clinicId: Number(process.env.SHEET_CLINIC_ID || 1),
  roomId: Number(process.env.SHEET_ROOM_ID || 1),
  serviceId: Number(process.env.SHEET_SERVICE_ID || 1),
  doctorId: Number(process.env.SHEET_DOCTOR_ID || 801),
}

let preparedAppointmentId = null

const nowIsoDate = (offsetDays = 0) => {
  const dt = new Date()
  dt.setDate(dt.getDate() + offsetDays)
  return dt.toISOString().slice(0, 10)
}

const parseJsonSafe = async (response) => {
  try {
    return await response.json()
  } catch {
    return null
  }
}

async function loginPatient(request) {
  const response = await request.post(`${API_BASE_URL}/api/auth/login`, {
    headers: { 'Content-Type': 'application/json' },
    data: {
      email: PATIENT_EMAIL,
      password: E2E_PASSWORD,
    },
  })

  const payload = await parseJsonSafe(response)
  if (!response.ok() || !payload?.token || !payload?.userId) {
    throw new Error(`Unable to login patient for appointment preparation. status=${response.status()}`)
  }

  return payload
}

async function listPatientAppointments(request, token, userId) {
  const response = await request.get(`${API_BASE_URL}/api/appointments/patient/${userId}`, {
    headers: { Authorization: `Bearer ${token}` },
    params: {
      page: 0,
      size: 100,
    },
  })
  const payload = await parseJsonSafe(response)
  if (!response.ok()) {
    throw new Error(`Unable to list patient appointments. status=${response.status()}`)
  }
  return Array.isArray(payload?.content) ? payload.content : []
}

async function confirmAppointment(request, token, appointmentId) {
  const response = await request.fetch(`${API_BASE_URL}/api/appointments/${appointmentId}/confirm`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
  })
  const body = await response.text().catch(() => '')
  return { status: response.status(), body }
}

async function createCandidateAppointment(request, token, userId) {
  const timeSlots = ['08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30']

  for (let dayOffset = 1; dayOffset <= 21; dayOffset += 1) {
    for (const timeSlot of timeSlots) {
      const response = await request.post(`${API_BASE_URL}/api/appointments`, {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        data: {
          patientId: userId,
          doctorId: DEFAULT_IDS.doctorId,
          familyMemberId: null,
          clinicId: DEFAULT_IDS.clinicId,
          serviceId: DEFAULT_IDS.serviceId,
          roomId: DEFAULT_IDS.roomId,
          serviceFee: 150000,
          appointmentDate: nowIsoDate(dayOffset),
          appointmentTime: timeSlot,
          durationMinutes: 30,
          type: 'IN_PERSON',
          symptoms: 'Generated by sheet automation',
          notes: 'Sheet auto test',
          priority: 'NORMAL',
        },
      })

      if (response.status() !== 201) {
        continue
      }

      const payload = await parseJsonSafe(response)
      const appointmentId = payload?.id || payload?.appointmentId || payload?.data?.id
      if (appointmentId) {
        return Number(appointmentId)
      }
    }
  }

  return null
}

async function prepareAppointmentIdForLifecycle(request) {
  const patient = await loginPatient(request)
  const token = patient.token
  const userId = patient.userId

  const appointments = await listPatientAppointments(request, token, userId)

  const confirmed = appointments.find((appointment) => appointment?.status === 'CONFIRMED')
  if (confirmed?.id) {
    return Number(confirmed.id)
  }

  const pending = appointments.filter((appointment) => appointment?.status === 'PENDING' && appointment?.id)
  for (const appointment of pending) {
    const confirmResult = await confirmAppointment(request, token, appointment.id)
    if (confirmResult.status === 200) {
      return Number(appointment.id)
    }
  }

  const createdId = await createCandidateAppointment(request, token, userId)
  if (createdId) {
    const confirmResult = await confirmAppointment(request, token, createdId)
    if (confirmResult.status === 200) {
      return Number(createdId)
    }
  }

  throw new Error('Unable to prepare a confirmed patient appointment for TC-041/TC-043')
}

function resolveCaseAppointmentId(testCase, appointmentId) {
  if (!appointmentId || !String(testCase.path).includes('/api/appointments/None')) {
    return testCase
  }

  const idString = String(appointmentId)
  return {
    ...testCase,
    path: String(testCase.path).replaceAll('None', idString),
    testStep: String(testCase.testStep).replaceAll('None', idString),
  }
}

const CASES = [
  {
    "id": "TC-041",
    "name": "Complete lịch",
    "module": "Appointment",
    "testStep": "PUT /api/appointments/None/complete",
    "expectedResult": "HTTP 200",
    "expectedStatus": 200,
    "method": "PUT",
    "path": "/api/appointments/None/complete",
    "qualifier": ""
  },
  {
    "id": "TC-042",
    "name": "Hủy lịch completed",
    "module": "Appointment",
    "testStep": "PUT /api/appointments/None/cancel",
    "expectedResult": "HTTP 400",
    "expectedStatus": 400,
    "method": "PUT",
    "path": "/api/appointments/None/cancel",
    "qualifier": ""
  },
  {
    "id": "TC-043",
    "name": "Feedback lịch",
    "module": "Appointment",
    "testStep": "PUT /api/appointments/None/feedback",
    "expectedResult": "HTTP 200",
    "expectedStatus": 200,
    "method": "PUT",
    "path": "/api/appointments/None/feedback",
    "qualifier": ""
  },
  {
    "id": "TC-044",
    "name": "Search lịch hẹn",
    "module": "Appointment",
    "testStep": "GET /api/appointments/search",
    "expectedResult": "HTTP 200",
    "expectedStatus": 200,
    "method": "GET",
    "path": "/api/appointments/search",
    "qualifier": ""
  },
  {
    "id": "TC-045",
    "name": "Xóa lịch 404",
    "module": "Appointment",
    "testStep": "DELETE /api/appointments/999999",
    "expectedResult": "HTTP 404",
    "expectedStatus": 404,
    "method": "DELETE",
    "path": "/api/appointments/999999",
    "qualifier": ""
  }
]

test.describe(`Sheet generated API suite | ${AGENT_NAME}`, () => {
  test.beforeAll(async ({ request }) => {
    if (!RUN_SHEET_GENERATED) {
      return
    }
    preparedAppointmentId = await prepareAppointmentIdForLifecycle(request)
  })

  test.beforeEach(() => {
    test.skip(!RUN_SHEET_GENERATED, 'Set RUN_SHEET_GENERATED=true to execute generated sheet tests')
  })

  for (const testCase of CASES) {
    test(`${testCase.id} | status contract | ${testCase.name}`, async ({ request }) => {
      const resolvedCase = resolveCaseAppointmentId(testCase, preparedAppointmentId)
      const result = await executeSheetCase(request, resolvedCase)
      expect(result.status, result.debug).toBe(resolvedCase.expectedStatus)
    })

    test(`${testCase.id} | latency budget | ${testCase.name}`, async ({ request }) => {
      const resolvedCase = resolveCaseAppointmentId(testCase, preparedAppointmentId)
      const result = await executeSheetCase(request, resolvedCase)
      expect(result.durationMs, result.debug).toBeLessThanOrEqual(15_000)
      expect(result.status, result.debug).toBeGreaterThanOrEqual(100)
      expect(result.status, result.debug).toBeLessThan(600)
    })
  }
})
